<?php

namespace ContainerHBixQjy;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kgpn3erService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kgpn3er' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kgpn3er'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contact' => ['privates', '.errored..service_locator.kgpn3er.App\\Entity\\Contact', NULL, 'Cannot autowire service ".service_locator.kgpn3er": it references class "App\\Entity\\Contact" but no such service exists.'],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'contact' => 'App\\Entity\\Contact',
            'manager' => '?',
        ]);
    }
}
