<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGOiwIEh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGOiwIEh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGOiwIEh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGOiwIEh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGOiwIEh\App_KernelDevDebugContainer([
    'container.build_hash' => 'GOiwIEh',
    'container.build_id' => '04ef56c1',
    'container.build_time' => 1633956790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGOiwIEh');
