<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFYCLaNB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFYCLaNB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFYCLaNB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFYCLaNB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFYCLaNB\App_KernelDevDebugContainer([
    'container.build_hash' => 'FYCLaNB',
    'container.build_id' => 'd105ffb9',
    'container.build_time' => 1633096608,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFYCLaNB');
