<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTZTIKlf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTZTIKlf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTZTIKlf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTZTIKlf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTZTIKlf\App_KernelDevDebugContainer([
    'container.build_hash' => 'TZTIKlf',
    'container.build_id' => 'b026e48e',
    'container.build_time' => 1633697422,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTZTIKlf');
