<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '' => [[], ['_controller' => 'App\\Controller\\Controller::index'], [], [['text', '/']], [], []],
    'presentation' => [[], ['_controller' => 'App\\Controller\\Controller::presentation'], [], [['text', '/presentation']], [], []],
    'exemple' => [[], ['_controller' => 'App\\Controller\\Controller::exemple'], [], [['text', '/exemple']], [], []],
    'avis' => [[], ['_controller' => 'App\\Controller\\Controller::avis'], [], [['text', '/avis']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
